Biblioteka/WebApplication_Library/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AuthDatabase.Entities;
using AutoMapper;
using DB_Model_EFCore.Controllers;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication_Library.Models;
using WebApplication_Library.Services;
using WebApplication_Library.ViewModels;
using Microsoft.AspNetCore.Identity;
using AuthDatabase.Entities;


namespace WebApplication_Library.Controllers
{
	public class ItemController : Controller
	{
		private readonly IAntiforgery _antiforgery;

		private readonly IBookService _bookService;
		private readonly UserManager<AppUser> _userManager;

		public ItemController(
	IBookService todoItemService,
	UserManager<AppUser> userManager)
		{
			_bookService = todoItemService;
			_userManager = userManager;
		}

		public async Task<IActionResult> Index()
        {
			var currentUser = await _userManager.GetUserAsync(User);
			if (currentUser == null)
			{
				return Challenge();
			}

			return View();
        }

		public IActionResult AddItem()
		{
			return View();
		}

		[HttpPost]
		public IActionResult AddItem(DB_Model_EFCore.Class.NewBook book)
		{
            Azure.CeateItem azure = new Azure.CeateItem();
            Task<string> url;
            string file;

            file = "c:\\temp\\m\\" + book.CoverName;
            url =azure.CeateNew(file);
            if (url.Result != null)
            {
                book.CoverName = url.Result;
                new BooksController().CreateNewBook(book);
            }

			return RedirectToAction(nameof(Statistics));
		}

		public IActionResult SearchItem()
		{
			return View();
		}

        [HttpGet]
        public IActionResult DetailsItem(int id)
		{
            DB_Model_EFCore.Class.Book book;
            List<DB_Model_EFCore.Class.Book> data = new DB_Model_EFCore.Controllers.BooksController().ListBooks();

            book =  (from DB_Model_EFCore.Class.Book item in data
                        where item.BookId == id
                        select item).FirstOrDefault();

            if (book != null)
            {
                BookDetailsVM item = new BookDetailsVM()
                {
                    BookName = book.BookName,
                    FirstName = book.FirstName,
                    LastName = book.LastName,
                    PublicationDate = book.PublicationDate,
                    CoverName = book.CoverName,
                    DataCarrierName = book.DataCarrierName,
                    BookId=book.BookId
                };

                DB_Model_EFCore.Class.BookRental rental;
                rental = new DB_Model_EFCore.Controllers.BooksRentalController().FindBookLastRental(book.BookId);

                if (rental != null)
                {
                    DB_Model_EFCore.Class.NewReader nReader = new DB_Model_EFCore.Class.NewReader();
                    DB_Model_EFCore.Controllers.ReaderController reader = new DB_Model_EFCore.Controllers.ReaderController();                   
                    nReader=reader.FindReader(rental.ReaderId.Value);

                    item.RentalId = rental.RentalId;
                    item.RentDateTime = rental.RentalDate.Value;
                    item.ReturnDateTime = rental.RentalDate.Value;
                    if (nReader != null)
                    {
                        item.RentalFirstName = nReader.FirstName;
                        item.RentalLastName = nReader.LastName;
                        item.RentalEmail = nReader.Email;
                    }
                }

                return View(item);
            }

            return NotFound();
        }

        [HttpPost]
        public IActionResult DetailsItem()
        {
            return RedirectToAction(nameof(Statistics));
        }

		public IActionResult ChangeStatusItem()
		{
			List<DB_Model_EFCore.Class.Book> data = new DB_Model_EFCore.Controllers.BooksController().ListBooks();
			return View(data);
		}

		[Route("/Rental/CreateNewBookRental/{id}/{type}")]
		[HttpPost]
		public async Task<IActionResult> ChangeStatusItem(int bookId, string comment)
		{
			{
				var currentUser = await _userManager.GetUserAsync(User);
				DB_Model_EFCore.Class.NewBookRental item = new DB_Model_EFCore.Class.NewBookRental();
				item.BookId = bookId;
				item.Comment = comment;
				item.ReaderId = Convert.ToInt16(currentUser.Id);
				new BooksRentalController().CreateNewBookRental(item,currentUser.FirstName,currentUser.LastName,currentUser.Email);
				return RedirectToAction(nameof(Statistics));
			}

		}

        //[Route("/PublicLibraryBook/ListBooks/{id}")]
        [HttpGet]
        public IActionResult RentItem(int id)
        {
            DB_Model_EFCore.Class.Book book;
            List<DB_Model_EFCore.Class.Book> data = new DB_Model_EFCore.Controllers.BooksController().ListBooks();

            book = (from DB_Model_EFCore.Class.Book item in data
                    where item.BookId == id
                    select item).FirstOrDefault();

            if (book != null)
            {
                BookDetailsVM item = new BookDetailsVM()
                {
                    BookName = book.BookName,
                    FirstName = book.FirstName,
                    LastName = book.LastName,
                    PublicationDate = book.PublicationDate,
                    CoverName = book.CoverName,
                    DataCarrierName = book.DataCarrierName,
                    BookId = id
                };

                DB_Model_EFCore.Class.BookRental rental;
                rental = new DB_Model_EFCore.Controllers.BooksRentalController().FindBookLastRental(id);

                if (rental == null || rental.ReturnDate!=null && rental.ReturnDate >= rental.RentalDate)
                {
                    return View(item);
                }
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> RentItem(BookDetailsVM itemVM)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            DB_Model_EFCore.Class.NewBookRental item = new DB_Model_EFCore.Class.NewBookRental();
            item.BookId = itemVM.BookId;
            item.Comment = itemVM.Comment;
            new BooksRentalController().CreateNewBookRental(item,currentUser.FirstName,currentUser.LastName,currentUser.Email);
            return RedirectToAction(nameof(Statistics));
        }

        [Route("/PublicLibraryBook/Book/{id}")]
		public async Task<IActionResult> DeleteBook(int id)
		{
			await _bookService.DeleteSomeID(id);
			//new DB_Model_EFCore.Controllers.BooksController().DeletetBook(id);
			return RedirectToAction(nameof(Statistics));
		}


		[Route("/PublicLibraryBook/ListBooks")]
		public async Task<IActionResult> Statistics()
		{

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("Statistics");
            }

            ICollection<BookViewModel> currentBookItems = await _bookService.GetAll();
            var model = new ListBookViewModel()
            {
                Items = currentBookItems
            };
            return View(model);


            //List<DB_Model_EFCore.Class.Book> data = new DB_Model_EFCore.Controllers.BooksController().ListBooks();

            //if (data == null)
            //{
            //    return NotFound();
            //}
            //return View(data);

        }
    }
}

Biblioteka/WebApplication_Library/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using AuthDatabase.Entities;

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteka domowa</title>
    <link rel="stylesheet" href="~/css/style.css" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Biblioteka domowa</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav ">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Menu</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Item" asp-action="Statistics">Wyszukaj pozycję</a> <br />
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <a class="dropdown-item" asp-area="" asp-controller="Item" asp-action="AddItem"> Dodaj pozycję </a> <br />
                                }
                                <!--<a class="dropdown-item" asp-area="" asp-controller="Item" asp-action="Statistics">Statystyki</a> <br />-->
                            </div>
                        </li>h
                        <li class="nav-item"> <a class="nav-link" asp-controller="Home" asp-action="About">O stronie</a></li>
                        <li class="nav-item"> <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a></li>

                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Zaloguj</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Zarejestruj</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <!--<a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">Witaj @UserManager.GetUserName(User) !</a>-->
                                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                                    <li class="nav-item">
                                    <button type="submit" class="btn btn-link navbar-btn navbar-link">Witaj @UserManager.GetUserName(User) !</button>
                                    </li>
                                </form>
                            </li>
                            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                                <li class="nav-item">
                                    <button type="submit" class="btn btn-link navbar-btn navbar-link">Wyloguj</button>
                                </li>
                            </form>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <hr />
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Biblioteka domowa 
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>